# Generated by Django 4.2 on 2023-04-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('salary', models.DecimalField(decimal_places=10, max_digits=19)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testfremvork.position')),
            ],
        ),
    ]
